### ISSUE TITLE
Switch to TypeScript

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/chord-magic#11]
I would like to use a similar method as in [blob-util](https://github.com/nolanlawson/blob-util) so that we can generate a `.d.ts` file and also automatically inject the documentation into the README.

**Comment by mdanka** [comment]
Hey @nolanlawson! I'm working on a site to create beautiful and usable guitar tabs with "syntax highlighting". One of the sub-projects would have been to create a chord parser, formatter, and auto-complete, but I was happy to see that you have already created something very thorough (and it looks excellent). If you're open to PRs and extensions, then I'd rather contribute here than create something new.

One of the first things before I can even use the library is having typings (my project is in typescript). Since it looks like you're working on switching to TypeScript, that looks like the best way to get typings (rather than a separate @types repo).

I see you've already assigned this issue to yourself. Are you looking for any help with it?

EDIT: in the meantime I created [momo-chords](https://github.com/mdanka/momo-chords), a typescript library for a very very large set of possible chord names.

**Comment by nolanlawson** [comment]
I would be happy to receive a PR for this. :) I'm not currently working on it, but it would be nice to have.

**Comment by mdanka** [comment]
Thanks :) In the meantime it was faster to create a separate library, with a different parsing system ([Github](https://github.com/mdanka/momo-chords)), you can even try it [here](https://momo-chords.miklosdanka.com/) if you're interested.

**Comment by nolanlawson** [comment]
No problem! :) Very cool, and nice work. I think I'll close this for now, since I may not have time to work on this.
